version: '3.1'
services:
  mongo:
    container_name: mongo_server
    image: mongo
    restart: always
    ports: 
      - 127.0.0.1:27017:27017
  server: 
    container_name: graphql_server
    build: 
      context: .
      dockerfile: GraphQLServer.dockerfile
    volumes: 
      - ./:/server
    entrypoint: 
      - ./entrypoint
    links: 
      - "mongo:database"
    ports: 
      - 127.0.0.1:3000:3000
    
    